name: Lint with ruff, check with mypy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weekly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * SUN"


jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy tqdm types-tqdm pandas pandas-stubs types-openpyxl
      - name: Install package
        run: |
          pip install .
      - name: Lint with ruff
        run: |
          # ruff check using toml settings. Ignore unused argument errors.
          ruff check .
      - name: Type check with mypy
        run: |
          # mypy check. Ignore uncheckable modules.
          mypy . --ignore-missing-imports
